# This is a basic workflow to help you get started with Actions

name: Beta Build and publish s3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ development ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_WEBSITE_PUBLISH }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_WEBSITE_PUBLISH }}
      AWS_DEFAULT_REGION: us-east-1
      CI: ""
      REACT_APP_API_URL: https://hangfive-web-api.herokuapp.com/
    steps: 
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: development
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 17.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Install Yarn  
        run: yarn
      - name: install dependencies
        run: |
          npx browserslist --update-db
          yarn build      

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1.2.4
        with:
          folder: build
          bucket: hangfive-web-beta
          dist-id: E11N4W2OVAB54T
          invalidation: "*"
